### ISSUE TITLE
Error compling with Borland C++ 3,  Undefined symbols

### ISSUE THREAD

**Issue by K1LL34** [kuroneko/fly8#1]
For some reason, the MSDOS side of the code will not compile because of undefined symbols 'RCV_AX', 'RCV_ES', 'RCV_DI', 'RCV_ID', & 'RCV_CX' in the function PuRecievePD in the file "pcudp.c".  There is likely a problem with the custom msdos packet driver.  I have included an image of the errors I recieved, hopefully it helps somewhat.

![command_000](https://user-images.githubusercontent.com/6275279/87215772-b8c00200-c307-11ea-8e80-f4613cf5605c.png)

My directory layout:
C:\SOURCE - This is where I keep various programming projects.
   \SOURCE\FLY8 - The main source files for fly8.
   \SOURCE\flib   - The support MSDOS libraries.
I have modified the makefiles to work with my filesystem layout.  All I changed were directory references to make it possible to compile my code.

There seems to be a problem with the support libraries.  That is as far as I can figure out.

**Comment by kuroneko** [comment]
The Borland port wasn't really maintained as heavily as the others, and as 1.12 was a Beta, I don't think the original author (and I certainly didn't) put significant effort into making sure it continued to work.

From my own recollection, the djgpp2 port was by far the most maintained and up to date of the DOS ports - if you really want to run it under DOS as it was 20 years ago, I would advise using that first.

Since the 1.12 branch and DOS sources are really only kept here as a bit of a record of where things ended, I won't be trying to fix this either.
